instrumentation:
    excludes:
        - ".vscode/*"
        - "config/*"
        - "media/*"
        - "resources/*"
        - ".vscodeignore"
        - "*.json"
        - "icon.png"
        - "*.txt"
        - "README.md"
        - "integrationTest/*"

check:
    global:
        statements: 100
        branches: 100
        functions: 100
        lines: 100
