pull_request_rules:
  - name: Add v2 pr label # Add v2 pr label to all PRs for v2 branch
    conditions:
      - base=v2
    actions:
      label:
        add:
          - v2 pr

  - name: Update tutorials
    conditions: []
    actions:
      comment:
        message: 'Please speak to the engagement team regarding updating tutorial & screenshots if any UI changes have been made!'