environment:
  nodejs_version: "8"
  CODE_DOWNLOAD_URL: https://vscode-update.azurewebsites.net/1.28.0/win32-x64-archive/stable
platform:
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g yo generator-fabric
  - cd client
  - npm install --no-optional
  - npm install --ignore-scripts
  - npm run compile
  - npm rebuild grpc --target=2.0.0 --runtime=electron --dist-url=https://atom.io/download/electron
  - if exist node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown ( rmdir /q/s node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown )
  - ren node_modules\grpc\src\node\extension_binary\electron-v2.0-win32-x64-unknown node-v57-win32-x64-unknown
  - cd ..
build: off
test_script:
  - cd client
  - npm test
  - cd ..