#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
